# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import safecollabapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('safecollabapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('owner', models.CharField(max_length=128)),
                ('encrypted', models.BooleanField()),
                ('upload', models.FileField(upload_to=safecollabapp.models.datafile_path)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=b'documents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportfile', models.FileField(upload_to=b'documents/%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='datafile',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safecollabapp.Report'),
        ),
    ]
